# Generated by Django 6.0.6 on 2026-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
