# Generated by Django 6.0.6 on 2026-07-29 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('designations', '0001_initial'),
        ('employees', '0003_employee_digital_signature'),
        ('locations', '0001_initial'),
        ('organizations', '0002_organization_official_stamp'),
        ('rbac', '0002_alter_permission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_code'), name='unique_employee_code_per_org'),
        ),
    ]
