# Generated by Django 6.0.6 on 2026-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='official_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='organization_stamps/'),
        ),
    ]
