# Generated by Django 6.0.6 on 2026-07-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0002_formsubmission_formsubmissionvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('email', 'Email'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('file', 'File')], max_length=20),
        ),
    ]
