# Generated by Django 6.0.6 on 2026-07-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0006_requestattachment'),
        ('organizations', '0002_organization_official_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
