# Generated by Django 6.0.6 on 2026-07-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_engine', '0008_alter_formsubmission_organization'),
        ('organizations', '0002_organization_official_stamp'),
        ('workflow', '0007_alter_workflowinstance_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinition',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='formdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_form_code_per_org'),
        ),
    ]
