# Generated by Django 6.0.6 on 2026-07-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('GUEST', 'Guest')], default='EMPLOYEE', max_length=20),
        ),
    ]
