# Generated by Django 6.0.6 on 2026-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
