# Generated by Django 6.0.6 on 2026-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SYSTEM', 'System Identity')], default='EMPLOYEE', max_length=20),
        ),
    ]
