# Generated by Django 6.0.6 on 2026-07-29 09:01

from django.db import migrations
from django.utils import timezone
from django.contrib.auth.hashers import make_password

def create_system_identity(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    
    # Create the inbound email processor if it doesn't exist
    User.objects.get_or_create(
        email="inbound_email_processor@system.local",
        defaults={
            "username": "inbound_email_processor",
            "first_name": "System",
            "last_name": "Inbound Email Processor",
            "user_type": "SYSTEM",
            "is_active": True,
            "is_staff": False,
            "is_superuser": False,
            "password": make_password(None), # Unusable password
            "is_email_verified": True,
            "created_at": timezone.now(),
            "updated_at": timezone.now(),
        }
    )

def remove_system_identity(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email="inbound_email_processor@system.local", user_type="SYSTEM").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.RunPython(create_system_identity, remove_system_identity),
    ]
