# Generated by Django 6.0.6 on 2026-07-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow.formdefinition')),
            ],
            options={
                'unique_together': {('form', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FormFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('DATETIME', 'DateTime'), ('BOOLEAN', 'Boolean'), ('SELECT', 'Select'), ('MULTISELECT', 'Multi Select'), ('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('FILE', 'File'), ('IMAGE', 'Image')], max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='workflow.formversion')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
    ]
