# Generated by Django 6.0.6 on 2026-07-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='approver_type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('ROLE', 'Role')], default='ROLE', max_length=20),
        ),
    ]
