# Generated by Django 6.0.6 on 2026-07-25 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflowstepdefinition_approver_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='specific_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowstepdefinition',
            name='approver_type',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('ROLE', 'Role'), ('SPECIFIC_USER', 'Specific User')], default='ROLE', max_length=20),
        ),
    ]
