# Generated by Django 6.0.6 on 2026-07-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_official_stamp'),
        ('workflow', '0006_workflowinstance_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
