# Generated by Django 6.0.6 on 2026-07-03 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('location_type', models.CharField(choices=[('HQ', 'Headquarters'), ('BRANCH', 'Branch'), ('FACTORY', 'Factory'), ('WAREHOUSE', 'Warehouse'), ('REMOTE', 'Remote Office'), ('DATACENTER', 'Data Center')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
