# Generated by Django 6.0.6 on 2026-08-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(max_length=100),
        ),
    ]
